   name: RagEval Project

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Execute the pytest and flake8
        run: make test
