from dataclasses import dataclass
from typing import Optional, Iterable
from transformers import AutoTokenizer

import datasets

from rageval.metrics import Metric, add_attribute


_DESCRIPTION = """\
ClaimNum is a metric designed to evaluate the richness of claims generated by the model. 

It is calculated by first utilizing the open-source tool RefChecker to extract claims from the generated text. The ultimate measure is the total number of distinct claims identified, providing insight into the diversity of opinions presented in the model's outputs.
"""

_KWARGS_DESCRIPTION = """\
Args:
    name : str

Optional Args:
    None

Functions:
    _compute_one: Evaluating the richness of claims generated.

Examples:
    >>> from datasets import Dataset
    >>> import rageval as rl
    >>> sample = {
    ...     "answers": [
    ...         "A",
    ...         "C",
    ...     ]
    ... }
    >>> dataset = Dataset.from_dict(sample)
    >>> metric = ClaimNum(openai_model="Qwen/Qwen2-0.5B-Instruct")
    >>> metric.mtype
    'answer_informativeness'
"""
