from dataclasses import dataclass
from typing import Optional, Iterable
from refchecker.extractor import LLMExtractor
import evaluate
import datasets
import os
from rageval.metrics import Metric, add_attribute


_DESCRIPTION = """\
ClaimNum is a metric designed to evaluate the richness of claims generated by the model. 

It is calculated by first utilizing the open-source tool RefChecker to extract claims from the generated text. The ultimate measure is the total number of distinct claims identified, providing insight into the diversity of opinions presented in the model's outputs.
"""

_KWARGS_DESCRIPTION = """\
Args:
    name : str

Optional Args:
    None

Functions:
    _compute_one: Evaluating the richness of claims generated.

Examples:
    >>> from datasets import Dataset
    >>> import rageval as rl
    >>> sample = {
    ...     "answers": [
    ...         "A",
    ...         "C",
    ...     ]
    ... }
    >>> dataset = Dataset.from_dict(sample)
    >>> metric = ClaimNum(model = "openai//home/gomall/models/Qwen2-7B-Instruct", api_base = "http://localhost:5000/v1", api_key = "sk-123456789")
    >>> metric.mtype
    'answer_informativeness'
"""

@dataclass
@add_attribute('mtype', 'answer_informativeness')
@datasets.utils.file_utils.add_start_docstrings(_DESCRIPTION, _KWARGS_DESCRIPTION)
class ClaimNum(Metric):
    """Estimates the richness of claims contained in answers."""

    name = "claim_num"

    ALIAS = ['claim_num']

    def __init__(self, model: str = "openai//home/gomall/models/Qwen2-7B-Instruct",
                 api_base: str = "http://localhost:5000/v1",
                 api_key: str = "sk-123456789"):
        """
        Explicitly initialize TextLength.

        Ensure all parent classes are initialized.
        """
        self.extractor = LLMExtractor(model=model, batch_size=8, api_base=api_base)
        os.environ['OPENAI_API_KEY'] = api_key
        super().__init__()
        self.info = evaluate.MetricInfo(
            description=_DESCRIPTION,
            inputs_description=_KWARGS_DESCRIPTION,
            citation="",
            homepage="",
            features=datasets.Features(
                {
                    "answers": datasets.Value("string"),
                }
            ),
            codebase_urls=[],
            reference_urls=[]
        )

    def __repr__(self) -> str:
        """:return: Formatted string representation of the metric."""
        return f"{self.ALIAS[0]}"  # pragma: no cover

    def _compute_one(
        self,
        answer: str,
        question: str,
        *args: Optional[Iterable],
    ) -> float:
        """Evaluating the richness of claims contained in answers."""
        extraction_results = self.extractor.extract(
            batch_responses=[answer],
            batch_questions=[question],
            max_new_tokens=1000
        )
        claims = [[c.content for c in res.claims] for  res in extraction_results]
        claim_num = len(claims[0])

        return claim_num