from dataclasses import dataclass
from typing import Optional, Iterable

import evaluate
import datasets
import os
from rageval.metrics import Metric, add_attribute
import numpy as np
from nltk.tokenize import sent_tokenize, word_tokenize
from collections import Counter


_DESCRIPTION = """\
Repetitiveness is a metric that evaluates repetitiveness/redundency generated by the model. 

It is calculated by first spliting answer into words unit and sentences. Then counts the apperance of same words and sentences diveded by the total number. Higher the number, higher the redundency.
"""

_KWARGS_DESCRIPTION = """\
Args:
    name : str

Optional Args:
    None

Functions:
    _compute_one: Evaluating the repetitiveness of answers generated.

Examples:
    >>> from datasets import Dataset
    >>> import rageval as rl
    >>> sample = {
    ...     "answers": [
    ...         "A",
    ...         "C",
    ...     ]
    ... }
    >>> dataset = Dataset.from_dict(sample)
    >>> metric = Repetitiveness()
    >>> metric.mtype
    'answer_informativeness'
"""

@dataclass
@add_attribute('mtype', 'answer_informativeness')
@datasets.utils.file_utils.add_start_docstrings(_DESCRIPTION, _KWARGS_DESCRIPTION)
class Repetitiveness(Metric):
    """Estimates the repetitiveness of answers."""

    name = "repetitiveness"

    ALIAS = ['repetitiveness']

    def __init__(self):
        """
        Explicitly initialize Repetitiveness.

        Ensure all parent classes are initialized.
        """
        super().__init__()
        self.info = evaluate.MetricInfo(
            description=_DESCRIPTION,
            inputs_description=_KWARGS_DESCRIPTION,
            citation="",
            homepage="",
            features=datasets.Features(
                {
                    "answers": datasets.Value("string"),
                }
            ),
            codebase_urls=[],
            reference_urls=[]
        )

    def __repr__(self) -> str:
        """:return: Formatted string representation of the metric."""
        return f"{self.ALIAS[0]}"  # pragma: no cover

    def _compute_one(
        self,
        answer: str,
        *args: Optional[Iterable],
    ) -> float:
        """Evaluating the repetitiveness of answer."""
        def generate_splits(text):
            words = word_tokenize(text)
            sentences = sent_tokenize(text)
            return words, sentences
        def calculate_redundancy_one(text):
            words, sentences = generate_splits(text)

            redundancy_ratio = []
            for gram in [words, sentences]:
                counts = Counter(gram)
                repeated_grams = sum(count for count in counts.values() if count > 1)
                redundancy_ratio.append(repeated_grams / len(gram) if len(gram) > 0 else 0)
            
            return np.mean(redundancy_ratio)
        scores = []

        return calculate_redundancy_one(answer)
