name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8.2"]

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: make init

    - name: Run check
      run: make test
