name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python version
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.1
        
    - name: Install requirements
      run: make init

    - name: Run check
      run: make test
